FROM arm32v7/python:3

WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn

COPY libmasterbus.so /usr/local/lib/
COPY api.py .

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
